### ISSUE TITLE
Valeur normalisée (entre 0 et 1), ne faut-il pas multiplier par une certaine amplitude? (taille du cluster ou équivalent)

### ISSUE THREAD

**Issue by youen** [CGI-FR/SIGO#14]
Valeur normalisée (entre 0 et 1), ne faut-il pas multiplier par une certaine amplitude? (taille du cluster ou équivalent)

_Originally posted by @Baguettte in https://github.com/CGI-FR/SIGO/pull/12#discussion_r790953115_

**Comment by Baguettte** [comment]
@giraud10 if fixed, close the issue
